name: 'Helm Artifactory Publisher'
description: GitHub Action for packaging, testing helm charts and publishing to Artifactory helm repo'
branding:
  icon: 'archive'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v3
    - run: ${{ github.action_path }}/main.sh ${{ inputs.action }}
      shell: bash
inputs:
  action:
    required: true
    description: "Action to perform: [check, dependency, lint, package, check_push, push]"
